export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const INCREASE_PRODUCT_AMOUNT = 'INCREASE_PRODUCT_AMOUNT';
export const DECREASE_PRODUCT_AMOUNT = 'DECREASE_PRODUCT_AMOUNT';
export const CLEAN_CART = 'CLEAN_CART';