export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const INCREASE_PRODUCT_QTY = 'INCREASE_PRODUCT_QTY';
export const DECREASE_PRODUCT_QTY = 'DECREASE_PRODUCT_QTY';
export const CLEAN_CART = 'CLEAN_CART';